app/core/views.py
# coding: utf-8
"""
Open Zeka Image Recognition Web & API Server
This is pre release version
http://openzeka.com
http://github.com/ferhatkurt/openzeka

Based on Flask-user starter app
"""


from flask import redirect, render_template, render_template_string, Blueprint
# OpenZeka: added jsonify
from flask import request, url_for, jsonify
from flask_user import current_user, login_required, roles_accepted
from app import app, db
# OpenZeka: added MyForm, ApplicationForm, ImageDemoForm, Client, Token, Usage
from app.core.models import UserProfileForm, MyForm, ApplicationForm, ImageDemoForm, Client, Token, Usage

# OpenZeka
from flask_user.signals import user_registered, user_confirmed_email
from datetime import datetime
import calendar
import requests, json
from werkzeug.security import gen_salt
# Caffe
import urllib
import cStringIO as StringIO
import logging
import caffe
import os
import werkzeug

core_blueprint = Blueprint('core', __name__, url_prefix='/')

# OpenZeka: New user registration save user ip address
@user_registered.connect_via(app)
def _track_registrations(sender, user, **extra):
    user.reg_ip = request.remote_addr
    db.session.add(user)
    db.session.commit()

# OpenZeka: After user email confirmation s processes will be done
@user_confirmed_email.connect_via(app)
def _track_confirmation(sender, user, **extra):
    i = datetime.now()
    usage_date = "%s,%s,%s" % (i.day, i.month, i.year)
    today = datetime.now()
    next_month = add_months(today, 1)
    item = Usage(
        user_id=user.id,
        # Adding 25000 limit. Limit information should be declare while registering
        usages=usage_date+","+str(next_month[0])+','+str(next_month[1])+','+str(next_month[2])+",0,25000"
    )
    db.session.add(item)
    db.session.commit()


# The Home page is accessible to anyone
@core_blueprint.route('')
def home_page():
    form=ImageDemoForm()
    return render_template('core/home_page.html', form=form)


# The User page is accessible to authenticated users (users that have logged in)
@core_blueprint.route('user')
@login_required  # Limits access to authenticated users
def user_page():
    return render_template('core/user_page.html')


# The Admin page is accessible to users with the 'admin' role
@core_blueprint.route('admin')
@roles_accepted('admin')  # Limits access to users with the 'admin' role
def admin_page():
    return render_template('core/admin_page.html')


@core_blueprint.route('user/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    form = UserProfileForm(request.form, current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)
        # Save user_profile
        db.session.commit()
        # Redirect to home page
        #return redirect(url_for('core.home_page'))
        # OpenZeka: After updating user will turn form page
        return redirect(url_for('core.user_profile_page'))

    # Process GET or invalid POST
    return render_template('core/user_profile_page.html',
                           form=form)

# Create client id and secret key
@core_blueprint.route('application/create', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def create_application():
    # Initialize form
    form = MyForm(request.form, current_user)
    user = current_user
    # Firsttime calling create_application
    if not (request.method == 'POST' and form.validate()):
        application_num = Client.query.filter_by(user_id=user.id).count()
        return render_template('application/create_application.html', form=form, application_number=application_num)
    # After entering application name and validation details adding to database
    item = Client(
        client_id=gen_salt(32),
        client_secret=gen_salt(32),
        application_name=request.form.get('application_name'),
        default_scope='api_access',
        _redirect_uris='https://api.openzeka.com/authorized ',
        user_id=user.id,
    )
    db.session.add(item)
    db.session.commit()
    form_application = ApplicationForm(request.form, item)
    return render_template('application/manage_application_page.html', application=item, form=form_application)

# Application edit id
@core_blueprint.route('application/edit/<id>', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def application_edit(id):
    application = Client.query.filter_by(application_id=id).first_or_404()
    form = ApplicationForm(request.form, application)
    # Firsttime calling create_application
    if request.method == 'POST' and form.validate():
        application.application_name = request.form.get('application_name')
        db.session.add(application)
        db.session.commit()
        active = application.application_id
        # user = current_user
        applications = Client.query.filter_by(user_id=application.user_id).all()
        number = Client.query.filter_by(user_id=application.user_id).count()
        return render_template('application/list_applications.html', applications=applications, number=number, active=active)

    return render_template('application/manage_application_page.html', application=application, form=form)

# Application delete id
@core_blueprint.route('application/delete/<id>', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def application_delete(id):
    client = Client.query.filter_by(application_id=id).first()
    token = Token.query.filter_by(client_id=client.client_id).first()
    if token:
        db.session.delete(token)
    db.session.delete(client)
    db.session.commit()

    return list_application()

# Create client id and secret key
@core_blueprint.route('application/list', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def list_application():
    user = current_user
    applications = Client.query.filter_by(user_id=user.id).all()
    app_first = Client.query.filter_by(user_id=user.id).first()
    form = ApplicationForm(request.form, app_first)
    number = Client.query.filter_by(user_id=user.id).count()
    # ilk applicasyonu secmek icin sorgu yapip active degerine id isini atadik
    active = 0
    if number > 0:
        active = app_first.application_id
    return render_template('application/list_applications.html', applications=applications, number=number, active=active, form=form)

@core_blueprint.route('save_token')
def save_token():
    client_id=request.args.get('client_id')
    client_secret=request.args.get('client_secret')
    grant_type='client_credentials'
    # result = request.post('http://localhost:9000/oauth/token', client_id)
    # data = 'client_id='+client_id+'&client_secret=HS6gm7JoGBFH41oWB2KSz85JqcDb5hoMiWDGQFZMWLRvdOtp3V&grant_type=client_credentials'

    # result = requests.post('http://localhost:9000/oauth/token', data=data)
    # result = requests.get('http://localhost:9000/oauth/token?client_id=0wd8Js7PoHy71me9wZ9kaPk1a1CtnkOPKMIq85iV&client_secret=i54wCpJSXOph2h0dKVaXAKcrBmaSHXdC1nWKh1BBWOGh2ng4D6&grant_type=client_credentials')
    result = requests.post('http://localhost:9000/oauth/token', data = {'client_id': client_id, 'client_secret': client_secret, 'grant_type': 'client_credentials'})
    json_data = json.loads(result.text)
    return jsonify(result=json_data['access_token'])
    # return jsonify(result=json_data)

# Usage sayfasi
@core_blueprint.route('usage')
@login_required  # Limits access to authenticated users
def usage_report():
    user = current_user
    usage_ = Usage.query.filter_by(user_id=user.id).first()
    # usages format: start day,month,year,end day,month,year,usage,limit;start day,month,year,end day,month,year,usage,limit;
    # sample: 15,7,2016,15,8,2016,15300,25000;15,8,2016,15,09,2016,20000,25000;15,9,2016,15,10,2016,1,25000
    if ';' in usage_.usages:
        months_with_usage = usage_.usages.split(";")
        # select latest month
        last_month_with_usage = months_with_usage.pop()
        last_month_with_usage = last_month_with_usage.split(",")
        has_old_month = True
        old_months_with_usage = reversed(months_with_usage)
    else:
        has_old_month = False
        old_months_with_usage = False
        last_month_with_usage = usage_.usages.split(",")
    today = datetime.now()
    past_month = last_month_with_usage
    past = datetime(int(past_month[5]), int(past_month[4]), int(past_month[3]))
    if (today > past):
        start_date = "%s,%s,%s" % (today.day, today.month, today.year)
        # start_date = datetime(int(latest_usage[2]), int(latest_usage[1]), int(latest_usage[0]))
        next_month = add_months(today, 1)
        # next_month = "1,9,2016"
        usage_.usages = usage_.usages + ";" + start_date + "," + str(next_month[0]) + ',' + str(
            next_month[1]) + ',' + str(next_month[2]) + ",0,25000"
        db.session.add(usage_)
        db.session.commit()
        # Normally this method should write again but we will recall samepage again.
        return redirect(url_for('core.usage_report'))
    return render_template('application/usage.html', has_old_month=has_old_month, old_months_with_usage=old_months_with_usage, latest_month=last_month_with_usage, progres_bar=progres_bar)

# Usage sayfasi
@core_blueprint.route('billing')
@login_required  # Limits access to authenticated users
def billing_page():
    # user = current_user
    # usage_ = Usage.query.filter_by(user_id=user.id).first()
    # user_limit=1000
    # usage_status = (usage_.usages/user_limit)*100

    # return render_template('core/billing.html', usage=usage_.usages, usage_status=usage_status)
    return render_template('application/billing.html')

# OpenZeka: Homepage demo form
@core_blueprint.route('classify_url', methods=['GET'])
def classify_url():
    # Dogrulama icin asagidaki gibi bir form cagiracagiz

app/templates/flask_user/change_password.html
{% extends "flask_user/member_base.html" %}
{% block user_content %}
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <!-- Content Block Container -->
                <div class="panel panel-default">
                    <div class="panel-body">
                        <!-- Title -->
                        <h4 class="text-center"><a href="{{ url_for('core.user_profile_page') }}" title="Profile">Edit
                            Profile</a></h4>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <!-- Content Block Container -->
                <div class="panel panel-default">
                    <div class="panel-body">
                        <!-- Title -->
                        <h4 class="text-center"><a href="{{ url_for('user.change_password') }}" title="Applications">Change
                            Password</a></h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <!-- Content Block Container -->
                <div class="panel panel-default">
                    <div class="panel-body edit-box">
                        <h2 class="text-center">{% trans %}Change password{% endtrans %}</h2>
                        {% from "common/form_macros.html" import render_field_openzeka,render_submit_button_openzeka, render_field, render_submit_field %}
                        <form action="" method="POST" class="form-horizontal" role="form">
                            <div class="row">
                                {{ form.hidden_tag() }}
                                {{ render_field_openzeka(form.old_password) }}
                                {{ render_field_openzeka(form.new_password) }}
                                {% if user_manager.enable_retype_password %}
                                    {{ render_field_openzeka(form.retype_password) }}
                                {% endif %}
                                <div class="col-xs-offset-4 col-sm-offset-4 col-md-offset-4 col-lg-offset-4">
                                    {{ render_submit_button_openzeka(form.submit, class="btn btn-success btn-block", label="Save Changes", text="Save Changes") }}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/flask_user/flask_user_base.html
{% extends "layout.html" %}
{% block pre_content %}{% endblock %}


{% block post_content %}{% endblock %}

app/templates/flask_user/forgot_password.html
{% extends 'flask_user/public_base.html' %}
{% from "common/form_macros.html" import render_field_openzeka, render_submit_field %}
{% block content %}
    <div class="col-sm-12">
        <div class="panel panel-default form-box">
            <div class="panel-body">
                <h1 class="text-center">{% trans %}Forgot Password{% endtrans %}</h1>
                <form action="" method="POST" class="form-horizontal" role="form">
                    {{ form.hidden_tag() }}
                    {{ render_field_openzeka(form.email) }}
                    {{ render_submit_field(form.submit, class="btn btn-primary btn-block") }}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/flask_user/login.html
{% extends 'flask_user/public_base.html' %}
{% from "common/form_macros.html" import render_checkbox_field_openzeka, render_field_openzeka, render_submit_field %}
{% block content %}
    <div class="col-sm-12">
        <div class="panel panel-default form-box">
            <div class="panel-body">
                <h1 class="text-center">{% trans %}Sign in{% endtrans %}</h1>
                <form action="" method="POST" class="form-horizontal" role="form">
                    {{ form.hidden_tag() }}

                    {# Username or Email field #}
                    {% set field = form.username if user_manager.enable_username else form.email %}
                    <div class="form-group {% if field.errors %}has-error{% endif %}">
                        <label for="{{ field.id }}" class="col-sm-4 control-label">{{ field.label.text }}</label>
                        <div class="col-sm-8">
                            {{ field(class_='form-control', placeholder= label|safe) }}
                            {% if field.errors %}
                                {% for e in field.errors %}
                                    <p class="help-block">{{ e }}</p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-sm-offset-4 col-sm-8 text-right">
                        {% if user_manager.enable_forgot_password %}
                            <a href="{{ url_for('user.forgot_password') }}">
                                {% trans %}Forgot your Password?{% endtrans %}</a>
                        {% endif %}
                    </div>
                    {# Password field #}
                    {% set field = form.password %}
                    <div class="form-group {% if field.errors %}has-error{% endif %}">
                        <label for="{{ field.id }}" class="col-sm-4 control-label">{{ field.label.text }}</label>
                        <div class="col-sm-8">
                            {{ field(class_='form-control', placeholder= label|safe) }}
                            {% if field.errors %}
                                {% for e in field.errors %}
                                    <p class="help-block">{{ e }}</p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    {# Remember me #}
                    {% if user_manager.enable_remember_me %}
                        {{ render_checkbox_field_openzeka(login_form.remember_me) }}
                    {% endif %}

                    {# Submit button #}
                    {{ render_submit_field(form.submit, class="btn btn-primary btn-block") }}

                    <!-- Title -->
                    {% if user_manager.enable_register and not user_manager.require_invitation %}
                        <div class="col-sm-offset-4 col-sm-8">
                            <div class="form-group text-center">
                                <h5>{% trans %}New here? Register.{% endtrans %}</h5>
                            </div>
                        </div><!-- /End Title -->
                        <!-- Sign IN -->
                        <div class="col-sm-offset-4 col-sm-8">
                            <div class="form-group">
                                <a href="{{ url_for('user.register') }}"
                                   title="{% trans %}New here? Register.{% endtrans %}"
                                   class="btn btn-success btn-block">{% trans %}Sign Up{% endtrans %}</a>
                            </div>
                        </div><!-- /End Sign IN -->
                    {% endif %}

                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/flask_user/member_base.html
{% extends 'flask_user/flask_user_base.html' %}
{% block content %}
    <div class="row">
        <!-- Title Block -->
        <div class="col-lg-10 col-lg-offset-1 col-md-12 title-block">
            <!-- Title Block Container -->
            <div class="title-block-container text-center">

                <!-- Title -->
                <h2>{% trans %}Welcome to User Page{% endtrans %}</h2>


            </div><!-- /End Title Block Container -->
        </div><!-- /End Title Block -->
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <!-- Content Block Container -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="list-group">
                        <a href="{{ url_for('core.user_profile_page') }}" title="Profile" class="list-group-item ">
                            <h2 class="list-group-item-heading"><span class="glyphicon glyphicon-edit"></span> Profile</h2>
                            <p class="list-group-item-text">Edit your profile.</p>
                        </a>
                        <a href="{{ url_for('core.list_application') }}" title="Applications" class="list-group-item">
                            <h2 class="list-group-item-heading"><span class="glyphicon glyphicon-plus"></span> Applications</h2>
                            <p class="list-group-item-text">Create and edit applications.</p>
                        </a>
                        <a href="{{ url_for('core.usage_report') }}" class="list-group-item">
                            <h2 class="list-group-item-heading"><span class="glyphicon glyphicon-stats"></span> Usage</h2>
                            <p class="list-group-item-text">Follow your monthly usage.</p>
                        </a>
                        <a href="{{ url_for('core.billing_page') }}" class="list-group-item list-group-item-info">
                            <h2 class="list-group-item-heading"><span class="glyphicon glyphicon-usd"></span> Billing</h2>
                            <p class="list-group-item-text">Change billing settings.</p>
                        </a>
                    </div>
                </div>

            </div><!-- /End Content Block Container -->
        </div>


        {% block user_content %}{% endblock %}

    </div>
{% endblock %}

app/templates/flask_user/public_base.html
{% extends 'flask_user/flask_user_base.html' %}

app/templates/flask_user/register.html
{% extends 'flask_user/public_base.html' %}
{% from "common/form_macros.html" import render_checkbox_field_openzeka, render_field_openzeka, render_submit_field %}
{% block content %}
<div class="col-sm-12">
<div class="panel panel-default form-box">
  <div class="panel-body">
  <h1 class="text-center">{%trans%}Register{%endtrans%}</h1>
<form action="" method="POST" novalidate formnovalidate class="form-horizontal" role="form">
    {{ form.hidden_tag() }}

    {# Username or Email #}
    {% set field = form.username if user_manager.enable_username else form.email %}
    <div class="form-group {% if field.errors %}has-error{% endif %}">
        <label for="{{ field.id }}" class="col-sm-4 control-label">{{ field.label.text }}</label>
        <div class="col-sm-8">
        {{ field(class_='form-control', placeholder= label|safe) }}
        {% if field.errors %}
            {% for e in field.errors %}
                 <label class="control-label">{{ e }}</label>
            {% endfor %}
        {% endif %}
    </div>
    </div>

    {% if user_manager.enable_email and user_manager.enable_username %}
        {{ render_field_openzeka(form.email) }}
    {% endif %}

    {{ render_field_openzeka(form.first_name) }}

    {{ render_field_openzeka(form.last_name) }}

    {{ render_field_openzeka(form.password) }}

    {% if user_manager.enable_retype_password %}
        {{ render_field_openzeka(form.retype_password) }}
    {% endif %}
    {{ render_checkbox_field_openzeka(form.signup_terms, class="form-control", label= 'I have read and agreed to OpenZeka <a href="#" title="terms and conditions">terms and conditions</a>.') }}

    {{ render_submit_field(form.submit, class="btn btn-primary btn-block") }}

                                            <!-- Title -->
                                        <div class="col-sm-offset-4 col-sm-8">
                                            <div class="form-group text-center">
                                                <h5>{%trans%}Already registered? Sign in.{%endtrans%}</h5>
                                            </div>
                                        </div><!-- /End Title -->
                                            <!-- Sign IN -->
                                        <div class="col-sm-offset-4 col-sm-8">
                                            <div class="form-group">
                                                <a href="{{ url_for('user.login') }}" title="Sign In" class="btn btn-success btn-block">{%trans%}Sign In{%endtrans%}</a>
                                            </div>
                                        </div><!-- /End Sign IN -->
</form>
  </div>
</div>
</div>


{% endblock %}