app/core/views.py
# coding: utf-8
"""
Open Zeka Image Recognition Web & API Server
This is pre release version
http://openzeka.com
http://github.com/ferhatkurt/openzeka

Based on Flask-user starter app
"""


from flask import redirect, render_template, render_template_string, Blueprint
# OpenZeka: added jsonify
from flask import request, url_for, jsonify
from flask_user import current_user, login_required, roles_accepted
from app import app, db
# OpenZeka: added MyForm, ApplicationForm, ImageDemoForm, Client, Token, Usage
from app.core.models import UserProfileForm, MyForm, ApplicationForm, ImageDemoForm, Client, Token, Usage

# OpenZeka
from flask_user.signals import user_registered, user_confirmed_email
from datetime import datetime
import calendar
import requests, json
from werkzeug.security import gen_salt
# Caffe
import urllib
import cStringIO as StringIO
import logging
import caffe
import os
import werkzeug

core_blueprint = Blueprint('core', __name__, url_prefix='/')

# OpenZeka: New user registration save user ip address
@user_registered.connect_via(app)
def _track_registrations(sender, user, **extra):
    user.reg_ip = request.remote_addr
    db.session.add(user)
    db.session.commit()

# OpenZeka: After user email confirmation s processes will be done
@user_confirmed_email.connect_via(app)
def _track_confirmation(sender, user, **extra):
    i = datetime.now()
    usage_date = "%s,%s,%s" % (i.day, i.month, i.year)
    today = datetime.now()
    next_month = add_months(today, 1)
    item = Usage(
        user_id=user.id,
        # Adding 25000 limit. Limit information should be declare while registering
        usages=usage_date+","+str(next_month[0])+','+str(next_month[1])+','+str(next_month[2])+",0,25000"
    )
    db.session.add(item)
    db.session.commit()


# The Home page is accessible to anyone
@core_blueprint.route('')
def home_page():
    form=ImageDemoForm()
    return render_template('core/home_page.html', form=form)


# The User page is accessible to authenticated users (users that have logged in)
@core_blueprint.route('user')
@login_required  # Limits access to authenticated users
def user_page():
    return render_template('core/user_page.html')


# The Admin page is accessible to users with the 'admin' role
@core_blueprint.route('admin')
@roles_accepted('admin')  # Limits access to users with the 'admin' role
def admin_page():
    return render_template('core/admin_page.html')


@core_blueprint.route('user/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    form = UserProfileForm(request.form, current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)
        # Save user_profile
        db.session.commit()
        # Redirect to home page
        #return redirect(url_for('core.home_page'))
        # OpenZeka: After updating user will turn form page
        return redirect(url_for('core.user_profile_page'))

    # Process GET or invalid POST
    return render_template('core/user_profile_page.html',
                           form=form)

# Create client id and secret key
@core_blueprint.route('application/create', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def create_application():
    # Initialize form
    form = MyForm(request.form, current_user)
    user = current_user
    # Firsttime calling create_application
    if not (request.method == 'POST' and form.validate()):
        application_num = Client.query.filter_by(user_id=user.id).count()
        return render_template('application/create_application.html', form=form, application_number=application_num)
    # After entering application name and validation details adding to database
    item = Client(
        client_id=gen_salt(32),
        client_secret=gen_salt(32),
        application_name=request.form.get('application_name'),
        default_scope='api_access',
        _redirect_uris='https://api.openzeka.com/authorized ',
        user_id=user.id,
    )
    db.session.add(item)
    db.session.commit()
    form_application = ApplicationForm(request.form, item)
    return render_template('application/manage_application_page.html', application=item, form=form_application)

# Application edit id
@core_blueprint.route('application/edit/<id>', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def application_edit(id):
    application = Client.query.filter_by(application_id=id).first_or_404()
    form = ApplicationForm(request.form, application)
    # Firsttime calling create_application
    if request.method == 'POST' and form.validate():
        application.application_name = request.form.get('application_name')
        db.session.add(application)
        db.session.commit()
        active = application.application_id
        # user = current_user
        applications = Client.query.filter_by(user_id=application.user_id).all()
        number = Client.query.filter_by(user_id=application.user_id).count()
        return render_template('application/list_applications.html', applications=applications, number=number, active=active)

    return render_template('application/manage_application_page.html', application=application, form=form)

# Application delete id
@core_blueprint.route('application/delete/<id>', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def application_delete(id):
    client = Client.query.filter_by(application_id=id).first()
    token = Token.query.filter_by(client_id=client.client_id).first()
    if token:
        db.session.delete(token)
    db.session.delete(client)
    db.session.commit()

    return list_application()

# Create client id and secret key
@core_blueprint.route('application/list', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def list_application():
    user = current_user
    applications = Client.query.filter_by(user_id=user.id).all()
    app_first = Client.query.filter_by(user_id=user.id).first()
    form = ApplicationForm(request.form, app_first)
    number = Client.query.filter_by(user_id=user.id).count()
    # ilk applicasyonu secmek icin sorgu yapip active degerine id isini atadik
    active = 0
    if number > 0:
        active = app_first.application_id
    return render_template('application/list_applications.html', applications=applications, number=number, active=active, form=form)

@core_blueprint.route('save_token')
def save_token():
    client_id=request.args.get('client_id')
    client_secret=request.args.get('client_secret')
    grant_type='client_credentials'
    # result = request.post('http://localhost:9000/oauth/token', client_id)
    # data = 'client_id='+client_id+'&client_secret=HS6gm7JoGBFH41oWB2KSz85JqcDb5hoMiWDGQFZMWLRvdOtp3V&grant_type=client_credentials'

    # result = requests.post('http://localhost:9000/oauth/token', data=data)
    # result = requests.get('http://localhost:9000/oauth/token?client_id=0wd8Js7PoHy71me9wZ9kaPk1a1CtnkOPKMIq85iV&client_secret=i54wCpJSXOph2h0dKVaXAKcrBmaSHXdC1nWKh1BBWOGh2ng4D6&grant_type=client_credentials')
    result = requests.post('http://localhost:9000/oauth/token', data = {'client_id': client_id, 'client_secret': client_secret, 'grant_type': 'client_credentials'})
    json_data = json.loads(result.text)
    return jsonify(result=json_data['access_token'])
    # return jsonify(result=json_data)

# Usage sayfasi
@core_blueprint.route('usage')
@login_required  # Limits access to authenticated users
def usage_report():
    user = current_user
    usage_ = Usage.query.filter_by(user_id=user.id).first()
    # usages format: start day,month,year,end day,month,year,usage,limit;start day,month,year,end day,month,year,usage,limit;
    # sample: 15,7,2016,15,8,2016,15300,25000;15,8,2016,15,09,2016,20000,25000;15,9,2016,15,10,2016,1,25000
    if ';' in usage_.usages:
        months_with_usage = usage_.usages.split(";")
        # select latest month
        last_month_with_usage = months_with_usage.pop()
        last_month_with_usage = last_month_with_usage.split(",")
        has_old_month = True
        old_months_with_usage = reversed(months_with_usage)
    else:
        has_old_month = False
        old_months_with_usage = False
        last_month_with_usage = usage_.usages.split(",")
    today = datetime.now()
    past_month = last_month_with_usage
    past = datetime(int(past_month[5]), int(past_month[4]), int(past_month[3]))
    if (today > past):
        start_date = "%s,%s,%s" % (today.day, today.month, today.year)
        # start_date = datetime(int(latest_usage[2]), int(latest_usage[1]), int(latest_usage[0]))
        next_month = add_months(today, 1)
        # next_month = "1,9,2016"
        usage_.usages = usage_.usages + ";" + start_date + "," + str(next_month[0]) + ',' + str(
            next_month[1]) + ',' + str(next_month[2]) + ",0,25000"
        db.session.add(usage_)
        db.session.commit()
        # Normally this method should write again but we will recall samepage again.
        return redirect(url_for('core.usage_report'))
    return render_template('application/usage.html', has_old_month=has_old_month, old_months_with_usage=old_months_with_usage, latest_month=last_month_with_usage, progres_bar=progres_bar)

# Usage sayfasi
@core_blueprint.route('billing')
@login_required  # Limits access to authenticated users
def billing_page():
    # user = current_user
    # usage_ = Usage.query.filter_by(user_id=user.id).first()
    # user_limit=1000
    # usage_status = (usage_.usages/user_limit)*100

    # return render_template('core/billing.html', usage=usage_.usages, usage_status=usage_status)
    return render_template('application/billing.html')

# OpenZeka: Homepage demo form
@core_blueprint.route('classify_url', methods=['GET'])
def classify_url():
    # Dogrulama icin asagidaki gibi bir form cagiracagiz

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/favicon.png') }}" sizes="32x32"/>

    <title>Open Zeka, Image Recognition Service</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{{ url_for('static', filename='bootstrap-3.3.7/assets/css/ie10-viewport-bug-workaround.css') }}"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='theme.css') }}" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="{{ url_for('static', filename='bootstrap-3.3.7/assets/js/ie8-responsive-file-warning.js') }}"></script>
    <![endif]-->
    <script src="{{ url_for('static', filename='bootstrap-3.3.7/assets/js/ie-emulation-modes-warning.js') }}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- HTML5 boilerplate CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='html5boilerplate/css/normalize.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='html5boilerplate/css/main.css') }}">
    <script src="{{ url_for('static', filename='html5boilerplate/js/modernizr-2.8.3.min.js') }}"></script>
</head>
<body>
{% block body %}

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><img src="{{ url_for('static', filename='images/logo.png') }}"
                                                      alt="Open Zeka" height="28"></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('core.home_page') }}">Home</a></li>
                    <li><a href="{{ url_for('core.user_page') }}">User</a></li>
                    <li><a href="{{ url_for('core.admin_page') }}">Admin</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li>
                            <a href="{{ url_for('core.user_page') }}"
                               class="btn btn-gfort wave-effect">{{ current_user.first_name or current_user.user_auth.username }}</a>
                        </li>

                        <li>
                            <a href="{{ url_for('user.logout') }}" class="btn">Sign out</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{{ url_for('user.login') }}" class="btn">Sign in</a>
                        </li>
                        <li>
                            <a href="{{ url_for('user.register') }}" title="Sign Up" class="btn ">Sign Up</a>
                        </li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container theme-showcase" role="main">

        {# One-time system messages called Flash messages #}
        {% block flash_messages %}
            {%- with messages = get_flashed_messages(with_categories=true) -%}
                {% if messages %}
                    {% for category, message in messages %}
                        {% if category=='error' %}
                            {% set category='danger' %}
                        {% endif %}
                        <div class="alert alert-{{ category }}">{{ message|safe }}</div>
                    {% endfor %}
                {% endif %}
            {%- endwith %}
        {% endblock %}

        <!-- Main jumbotron for a primary marketing message or call to action -->

        {% block pre_content %}{% endblock %}

        {% block content %}{% endblock %}

        {% block post_content %}{% endblock %}


    </div>
    {#    <div class="oz_space_up text-hide"></div>#}
    <div class="oz_space_up_40">
        <footer class="footer">
            <div class="container">
                <div class="text-muted"><a href="http://openzeka.com">Open Zeka</a> ||
                    <a href="https://github.com/ferhatkurt/openzeka">Github</a> ||
                    <a href="https://twitter.com/openzeka">Twitter</a> ||
                    <a href="https://groups.google.com/forum/#!forum/open-zeka">Google Groups</a>
                    <span class="navbar-right">Open Zeka {{ config['OPENZEKA_VERSION'] }}</span></div>
            </div>
        </footer>
    </div>
    <script src="{{ url_for('static', filename='js/jquery-3.1.1.min.js') }} "></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }} "></script>
    <script src="{{ url_for('static', filename='js/bootstrap-confirmation.min.js') }} "></script>
    <!-- HTML5 boilerplate JS -->
    <script src="{{ url_for('static', filename='html5boilerplate/js/main.js') }} "></script>
    <!--Plug-in Initialisation-->
    {#    Check below tab script#}
    <script src="{{ url_for('static', filename='theme.js') }} "></script>
{% endblock %}
</body>
</html>