app/core/views.py
# coding: utf-8
"""
Open Zeka Image Recognition Web & API Server
This is pre release version
http://openzeka.com
http://github.com/ferhatkurt/openzeka

Based on Flask-user starter app
"""


from flask import redirect, render_template, render_template_string, Blueprint
# OpenZeka: added jsonify
from flask import request, url_for, jsonify
from flask_user import current_user, login_required, roles_accepted
from app import app, db
# OpenZeka: added MyForm, ApplicationForm, ImageDemoForm, Client, Token, Usage
from app.core.models import UserProfileForm, MyForm, ApplicationForm, ImageDemoForm, Client, Token, Usage

# OpenZeka
from flask_user.signals import user_registered, user_confirmed_email
from datetime import datetime
import calendar
import requests, json
from werkzeug.security import gen_salt
# Caffe
import urllib
import cStringIO as StringIO
import logging
import caffe
import os
import werkzeug

core_blueprint = Blueprint('core', __name__, url_prefix='/')

# OpenZeka: New user registration save user ip address
@user_registered.connect_via(app)
def _track_registrations(sender, user, **extra):
    user.reg_ip = request.remote_addr
    db.session.add(user)
    db.session.commit()

# OpenZeka: After user email confirmation s processes will be done
@user_confirmed_email.connect_via(app)
def _track_confirmation(sender, user, **extra):
    i = datetime.now()
    usage_date = "%s,%s,%s" % (i.day, i.month, i.year)
    today = datetime.now()
    next_month = add_months(today, 1)
    item = Usage(
        user_id=user.id,
        # Adding 25000 limit. Limit information should be declare while registering
        usages=usage_date+","+str(next_month[0])+','+str(next_month[1])+','+str(next_month[2])+",0,25000"
    )
    db.session.add(item)
    db.session.commit()


# The Home page is accessible to anyone
@core_blueprint.route('')
def home_page():
    form=ImageDemoForm()
    return render_template('core/home_page.html', form=form)


# The User page is accessible to authenticated users (users that have logged in)
@core_blueprint.route('user')
@login_required  # Limits access to authenticated users
def user_page():
    return render_template('core/user_page.html')


# The Admin page is accessible to users with the 'admin' role
@core_blueprint.route('admin')
@roles_accepted('admin')  # Limits access to users with the 'admin' role
def admin_page():
    return render_template('core/admin_page.html')


@core_blueprint.route('user/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    form = UserProfileForm(request.form, current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)
        # Save user_profile
        db.session.commit()
        # Redirect to home page
        #return redirect(url_for('core.home_page'))
        # OpenZeka: After updating user will turn form page
        return redirect(url_for('core.user_profile_page'))

    # Process GET or invalid POST
    return render_template('core/user_profile_page.html',
                           form=form)

# Create client id and secret key
@core_blueprint.route('application/create', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def create_application():
    # Initialize form
    form = MyForm(request.form, current_user)
    user = current_user
    # Firsttime calling create_application
    if not (request.method == 'POST' and form.validate()):
        application_num = Client.query.filter_by(user_id=user.id).count()
        return render_template('application/create_application.html', form=form, application_number=application_num)
    # After entering application name and validation details adding to database
    item = Client(
        client_id=gen_salt(32),
        client_secret=gen_salt(32),
        application_name=request.form.get('application_name'),
        default_scope='api_access',
        _redirect_uris='https://api.openzeka.com/authorized ',
        user_id=user.id,
    )
    db.session.add(item)
    db.session.commit()
    form_application = ApplicationForm(request.form, item)
    return render_template('application/manage_application_page.html', application=item, form=form_application)

# Application edit id
@core_blueprint.route('application/edit/<id>', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def application_edit(id):
    application = Client.query.filter_by(application_id=id).first_or_404()
    form = ApplicationForm(request.form, application)
    # Firsttime calling create_application
    if request.method == 'POST' and form.validate():
        application.application_name = request.form.get('application_name')
        db.session.add(application)
        db.session.commit()
        active = application.application_id
        # user = current_user
        applications = Client.query.filter_by(user_id=application.user_id).all()
        number = Client.query.filter_by(user_id=application.user_id).count()
        return render_template('application/list_applications.html', applications=applications, number=number, active=active)

    return render_template('application/manage_application_page.html', application=application, form=form)

# Application delete id
@core_blueprint.route('application/delete/<id>', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def application_delete(id):
    client = Client.query.filter_by(application_id=id).first()
    token = Token.query.filter_by(client_id=client.client_id).first()
    if token:
        db.session.delete(token)
    db.session.delete(client)
    db.session.commit()

    return list_application()

# Create client id and secret key
@core_blueprint.route('application/list', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def list_application():
    user = current_user
    applications = Client.query.filter_by(user_id=user.id).all()
    app_first = Client.query.filter_by(user_id=user.id).first()
    form = ApplicationForm(request.form, app_first)
    number = Client.query.filter_by(user_id=user.id).count()
    # ilk applicasyonu secmek icin sorgu yapip active degerine id isini atadik
    active = 0
    if number > 0:
        active = app_first.application_id
    return render_template('application/list_applications.html', applications=applications, number=number, active=active, form=form)

@core_blueprint.route('save_token')
def save_token():
    client_id=request.args.get('client_id')
    client_secret=request.args.get('client_secret')
    grant_type='client_credentials'
    # result = request.post('http://localhost:9000/oauth/token', client_id)
    # data = 'client_id='+client_id+'&client_secret=HS6gm7JoGBFH41oWB2KSz85JqcDb5hoMiWDGQFZMWLRvdOtp3V&grant_type=client_credentials'

    # result = requests.post('http://localhost:9000/oauth/token', data=data)
    # result = requests.get('http://localhost:9000/oauth/token?client_id=0wd8Js7PoHy71me9wZ9kaPk1a1CtnkOPKMIq85iV&client_secret=i54wCpJSXOph2h0dKVaXAKcrBmaSHXdC1nWKh1BBWOGh2ng4D6&grant_type=client_credentials')
    result = requests.post('http://localhost:9000/oauth/token', data = {'client_id': client_id, 'client_secret': client_secret, 'grant_type': 'client_credentials'})
    json_data = json.loads(result.text)
    return jsonify(result=json_data['access_token'])
    # return jsonify(result=json_data)

# Usage sayfasi
@core_blueprint.route('usage')
@login_required  # Limits access to authenticated users
def usage_report():
    user = current_user
    usage_ = Usage.query.filter_by(user_id=user.id).first()
    # usages format: start day,month,year,end day,month,year,usage,limit;start day,month,year,end day,month,year,usage,limit;
    # sample: 15,7,2016,15,8,2016,15300,25000;15,8,2016,15,09,2016,20000,25000;15,9,2016,15,10,2016,1,25000
    if ';' in usage_.usages:
        months_with_usage = usage_.usages.split(";")
        # select latest month
        last_month_with_usage = months_with_usage.pop()
        last_month_with_usage = last_month_with_usage.split(",")
        has_old_month = True
        old_months_with_usage = reversed(months_with_usage)
    else:
        has_old_month = False
        old_months_with_usage = False
        last_month_with_usage = usage_.usages.split(",")
    today = datetime.now()
    past_month = last_month_with_usage
    past = datetime(int(past_month[5]), int(past_month[4]), int(past_month[3]))
    if (today > past):
        start_date = "%s,%s,%s" % (today.day, today.month, today.year)
        # start_date = datetime(int(latest_usage[2]), int(latest_usage[1]), int(latest_usage[0]))
        next_month = add_months(today, 1)
        # next_month = "1,9,2016"
        usage_.usages = usage_.usages + ";" + start_date + "," + str(next_month[0]) + ',' + str(
            next_month[1]) + ',' + str(next_month[2]) + ",0,25000"
        db.session.add(usage_)
        db.session.commit()
        # Normally this method should write again but we will recall samepage again.
        return redirect(url_for('core.usage_report'))
    return render_template('application/usage.html', has_old_month=has_old_month, old_months_with_usage=old_months_with_usage, latest_month=last_month_with_usage, progres_bar=progres_bar)

# Usage sayfasi
@core_blueprint.route('billing')
@login_required  # Limits access to authenticated users
def billing_page():
    # user = current_user
    # usage_ = Usage.query.filter_by(user_id=user.id).first()
    # user_limit=1000
    # usage_status = (usage_.usages/user_limit)*100

    # return render_template('core/billing.html', usage=usage_.usages, usage_status=usage_status)
    return render_template('application/billing.html')

# OpenZeka: Homepage demo form
@core_blueprint.route('classify_url', methods=['GET'])
def classify_url():
    # Dogrulama icin asagidaki gibi bir form cagiracagiz

app/templates/application/billing.html
{% extends 'flask_user/member_base.html' %}
{% block user_content %}
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <!-- Content Block Container -->
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h1 class="text-center">
                            <span class="label label-danger">FREE</span>
                            <span class="label label-info">25.000 Requests/Month</span>
                            <span class="label label-info">API Access</span>
                            <span class="label label-info">Image Tagging</span>
                            <span class="label label-info">E-mail Support</span>
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/application/create_application.html
{% extends 'flask_user/member_base.html' %}
{% from "common/form_macros.html" import render_field, render_submit_field, render_field_openzeka %}
{% block user_content %}
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
        <div class="row">

            <div class="panel panel-default">
                <div class="panel-body">
                    {% if application_number >= 10 %}
                    <h2 class="alert-danger text-center">You Reached The Application Limit</h2>
                    <div class="progress">
                        <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"
                             aria-valuenow="100"
                             aria-valuemin="0"
                             aria-valuemax="100" style="min-width: 4em;width: 100%">
                            100%</span>
                        </div>
                    </div>
                    <!-- Description -->
                    <p>You can delete unused applications or contact us for the increasing application limit</p>
                    {% else %}
                        <h1 class="text-center">{% trans %}New Application{% endtrans %}</h1>
                    <form action="" method="POST" novalidate formnovalidate class="form-horizontal" role="form">
                        {{ form.hidden_tag() }}
                        {{ render_field_openzeka(form.application_name) }}
                        {{ render_submit_field(form.submit, class="btn btn-primary btn-block") }}
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/application/list_applications.html
{% extends 'flask_user/member_base.html' %}
{% from "common/form_macros.html" import render_field, render_submit_field, render_field_openzeka %}
{% block user_content %}
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
        <div class="row">
            <div class="col-x-12 col-sm-12 col-md-4 col-lg-4 oz_right">
                <ul class="nav nav-tabs nav-stacked text-left" role="tablist">
                    {% for entry in applications %}
                        <li role="presentation" {% if entry.application_id == active %} class="active" {% endif %}>
                            <a href="#{{ entry.application_id }}" aria-controls="{{ entry.application_id }}" role="tab"
                               data-toggle="tab">
                                <span>{{ entry.application_name }}</span>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 oz_left">
                <div class="tab-content">
                    {% for entry in applications %}
                        <!-- Event Tab 1 -->
                        <div id="{{ entry.application_id }}"
                             class="tab-pane fade {% if entry.application_id == active %} in active{% endif %}"
                             role="tabpanel">
                            <!-- Widget Block Content -->
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <div class="row row-height">
                                        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 bg-success text-success">
                                            Name
                                        </div>
                                        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9 bg-success text-success">
                                            {{ entry.application_name }}
                                        </div>
                                    </div>
                                    <div class="row row-height">
                                        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 bg-warning text-warning">
                                            Model
                                        </div>
                                        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9 bg-warning text-warning">
                                            General v1
                                        </div>
                                    </div>
                                    <div class="row row-height">
                                        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 bg-success text-success">
                                            Client Type
                                        </div>
                                        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9 bg-success text-success">
                                            {{ entry.application_name }}
                                        </div>
                                    </div>
                                    <div class="row row-height">
                                        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 bg-warning text-warning">
                                            Grant Type
                                        </div>
                                        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9 bg-warning text-warning">
                                            Confidential
                                        </div>
                                    </div>
                                    <div class="row row-height">
                                        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 bg-success text-success">
                                            Scopes
                                        </div>
                                        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9 bg-success text-success">
                                            {{ entry.default_scope }}
                                        </div>
                                    </div>
                                    <div class="row row-height">
                                        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 bg-warning text-warning">
                                            Client Id
                                        </div>
                                        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9 bg-warning text-warning">
                                            {{ entry.client_id }}
                                        </div>
                                    </div>
                                    <div class="row row-height">
                                        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 bg-success text-success">
                                            Client Secret
                                        </div>
                                        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9 bg-success text-success">
                                            {{ entry.client_secret }}
                                        </div>
                                    </div>
                                    <div class="row row-height">
                                        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 bg-warning text-danger">
                                            <a href="#{{ entry.client_id }}#{{ entry.client_secret }}"
                                               title="Generate Token"
                                               id="generate_token"><span
                                                    class="glyphicon glyphicon-refresh glyphicon-spin"></span>Token</a>
                                        </div>
                                        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9 bg-warning text-danger"
                                             id="client_token{{ entry.client_id }}">
                                            <a href="#{{ entry.client_id }}#{{ entry.client_secret }}"
                                               title="Generate Token"
                                               id="generate_token">Click Here to Generate Token</a>
                                        </div>
                                    </div>
                                    <div class="row oz-space-up-20">
                                        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                            <a href="{{ url_for('core.application_edit', id=entry.application_id) }}"
                                               title="Edit" class="btn btn-success btn-block">Edit Application</a>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                            <a data-href="{{ url_for('core.application_delete', id=entry.application_id) }}"
                                               title="Delete Application?" class="btn btn-danger btn-block"
                                               data-toggle="confirmation" data-placement="top">Delete</a>
                                        </div>
                                    </div>
                                </div><!-- /End Widget Block Content -->
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% if number >= 10 %}
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h2 class="text-center">You Reached The Application Limit</h2>
            <p class="text-center text-danger">You can delete unused applications or contact us for the increasing
                application limit.</p>
        </div>
    {% else %}
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
            <div class="text-success"><h3>Application limit {{ number }}/10</h3></div>
            <div class="progress">
                <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"
                     aria-valuenow="{{ number }}0"
                     aria-valuemin="0"
                     aria-valuemax="100" style="min-width: 4em;width: {{ number }}0%">
                    {{ number }}0%</span>
                </div>
            </div>
        </div>
        <div class="{% if number == 0 %}col-xs-12 col-sm-8 col-md-8 col-lg-8{% else %}col-xs-12 col-sm-12 col-md-12 col-lg-12{% endif %} button-block">
            <div class="text-center oz-space-up-20">
                <a href="{{ url_for('core.create_application') }}" title="Create a New Application"
                   class="btn btn-primary">Create a New Application</a>
            </div>
        </div><!-- /End button-block -->
    {% endif %}
{% endblock %}

app/templates/application/manage_application_page.html
{% extends 'flask_user/member_base.html' %}
{% from "common/form_macros.html" import render_field, render_submit_field, render_field_openzeka %}
{% block user_content %}
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
        <div class="panel panel-default">
            <div class="panel-body">
                <h2 class="text-center">{% trans %}Edit Application{% endtrans %}</h2>
                <form action="" method="POST" novalidate formnovalidate class="form-horizontal" role="form">
                    {{ form.hidden_tag() }}
                    {{ render_field_openzeka(form.application_name, value=application.application_name) }}
                    {{ render_field_openzeka(form.client_id, value=application.client_id, readonly=true) }}
                    {{ render_field_openzeka(form.client_secret, value=application.client_secret, readonly=true) }}
                    <div class="form-group">
                        <label for="client_token" class="col-sm-4 control-label"><strong><a
                                href="#{{ application.client_id }}#{{ application.client_secret }}"
                                title="Generate Token"
                                id="generate_token"><span
                                class="glyphicon glyphicon-refresh glyphicon-spin"></span>Generate
                            Token</a></strong></label></span>
                        <div class="col-sm-8">
                            <strong><span id="client_token{{ application.client_id }}"></span></strong>
                        </div>
                    </div>
                    {{ render_submit_field(form.submit, class="btn btn-primary btn-block") }}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/application/usage.html
{% extends 'flask_user/member_base.html' %}
{% block user_content %}
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
        <div class="panel panel-default">
            <div class="panel-body">
                {% set usage_status = (latest_month[6]|int / latest_month[7]|int) * 100 %}
                <div>Latest Month - Usage limit {{ latest_month[6] }}/{{ latest_month[7] }}</div>
                <div class="progress">
                    <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"
                         aria-valuenow="{{ usage_status }}"
                         aria-valuemin="0"
                         aria-valuemax="100" style="min-width: 4em;width: {{ usage_status }}%">
                        {{ usage_status }}%</span>
                    </div>
                </div>
                <div class="text-center">{{ latest_month[0]+','+latest_month[1]+','+latest_month[2] }}
                    - {{ latest_month[3]+','+latest_month[4]+','+latest_month[5] }}</div>
            </div>
        </div>

        {% if has_old_month %}
            <div>Old Usages</div>
            {% for month in old_months_with_usage %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% set latest_month = month.split(',') %}
                        {% set usages_status = (latest_month[6]|int / latest_month[7]|int) * 100 %}
                        <div>Usage limit {{ latest_month[6] }}/{{ latest_month[7] }}</div>
                        <div class="progress">
                            <div class="progress-bar progress-bar{{ progres_bar[(loop.index)] }} progress-bar-striped" role="progressbar"
                                 aria-valuenow="{{ usages_status }}"
                                 aria-valuemin="0"
                                 aria-valuemax="100" style="min-width: 4em;width: {{ usages_status }}%">
                                {{ usages_status }}%</span>
                            </div>
                        </div>
                        <div class="text-center">{{ latest_month[0]+','+latest_month[1]+','+latest_month[2] }}
                            - {{ latest_month[3]+','+latest_month[4]+','+latest_month[5] }}</div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}